=== hifive/hifivetools/eclipse/H5ProjectWizardPlugin/test/com/htmlhifive/tools/wizard/library/model/xml/libraries.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xsd:schema xmlns="http://www.htmlhifive.com/schema/libraries" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.htmlhifive.com/schema/libraries">

	<xsd:element name="libraries">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="site-libraries" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="default-libraries" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="base-projects" maxOccurs="1" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="library">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="site" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="version" type="version" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="category">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="info" maxOccurs="unbounded" minOccurs="0" />
				<xsd:element ref="license" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="library" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="org" use="required">
				<xsd:simpleType>
					<xsd:restriction base="org"></xsd:restriction>
				</xsd:simpleType>
			</xsd:attribute>
			<xsd:attribute name="name" type="categoryName" use="required" />
			<xsd:attribute name="path" type="xsd:normalizedString" use="required" />
			<xsd:attribute name="licenseUrl" type="xsd:anyURI" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="site">
		<xsd:complexType>
			<xsd:attribute name="url" type="url" use="required" />
			<xsd:attribute name="file-pattern" type="xsd:normalizedString" />
			<xsd:attribute name="extract-path" type="xsd:normalizedString" />
			<xsd:attribute name="replace-file-name" type="siteName" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="default-libraries">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="library-ref" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="library-ref">
		<xsd:complexType>
			<xsd:attribute name="org" type="org" use="required" />
			<xsd:attribute name="name" type="categoryName" use="required" />
			<xsd:attribute name="version" type="version" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="org">
		<xsd:restriction base="xsd:normalizedString"></xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="categoryName">
		<xsd:restriction base="xsd:normalizedString"></xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="version">
		<xsd:restriction base="xsd:NMTOKEN"></xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="url">
		<xsd:restriction base="xsd:anyURI"></xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="siteName">
		<xsd:restriction base="xsd:normalizedString"></xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="license">
		<xsd:simpleType>
			<xsd:restriction base="xsd:string"></xsd:restriction>
		</xsd:simpleType>
	</xsd:element>

	<xsd:element name="site-libraries">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="category" maxOccurs="unbounded" minOccurs="0" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="base-project">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="info" maxOccurs="unbounded" minOccurs="1" />
				<xsd:element ref="replace" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="natures" maxOccurs="1" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="url" type="url" use="required" />
			<xsd:attribute name="default-js-lib-path" type="xsd:normalizedString" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="info">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="title" maxOccurs="1" minOccurs="0" />
				<xsd:element ref="description" maxOccurs="1" minOccurs="0" />
			</xsd:sequence>
			<xsd:attribute name="lang" type="lang" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="base-projects">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="base-project" maxOccurs="unbounded" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="title" type="xsd:normalizedString" />

	<xsd:element name="description" type="xsd:string" />

	<xsd:simpleType name="lang">
		<xsd:restriction base="xsd:language"></xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="replace">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="file" maxOccurs="unbounded" minOccurs="1" />
			</xsd:sequence>
			<xsd:attribute name="target" type="xsd:normalizedString" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="file">
		<xsd:complexType>
			<xsd:attribute name="name" type="xsd:normalizedString" use="required" />
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="natures">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="nature" maxOccurs="unbounded" minOccurs="1" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="nature">
		<xsd:complexType>
			<xsd:attribute name="id" type="xsd:NMTOKEN" use="required" />
			<xsd:attribute name="name" type="xsd:normalizedString" />
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== hifive/hifivetools/eclipse/H5ProjectWizardPlugin/site-resources-local/local-libraries.xml
<?xml version="1.0" encoding="UTF-8"?>
<libraries xmlns="http://www.htmlhifive.com/schema/libraries" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.htmlhifive.com/schema/libraries libraries.xsd ">

	<site-libraries>
		<category org="hifive" name="hifive" path="${default.js.lib.path}/h5">
<license><![CDATA[
Copyright (C) 2012 NS Solutions Corporation

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    <a>http://www.apache.org/licenses/LICENSE-2.0</a>

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

<a>http://www.htmlhifive.com</a>
]]></license>
			<info>
				<title>hifive library</title>
				<description>hifive base library</description>
			</info>
			<info lang="ja">
				<title>hifive ライブラリ</title>
				<description><![CDATA[
hifive の動作に必要なライブラリ
<a>http://www.htmlhifive.com</a>
				]]></description>
			</info>
			<library version="1.0.4">
				<site url="/archives/v1.0.4/ejs-1.0.h5mod.js" />
				<site url="/archives/v1.0.4/h5-1.0.4.css" />
				<site url="/archives/v1.0.4/h5-1.0.4.dev.js" />
				<site url="/archives/v1.0.4/h5-1.0.4.js" />
			</library>
		</category>
	</site-libraries>


	<default-libraries>
		<library-ref org="hifive" name="hifive" version="1.0.4" />
	</default-libraries>


	<base-projects>
		<base-project default-js-lib-path="WebContent/res/lib" url="/projects/wtp.zip">
			<info lang="ja">
				<title>hifive 基本構成 WTP プロジェクト</title>
				<description>[hifive利用時の基本構成]
				・JavaSriptプロジェクト
				・WebContentsがドキュメントルートの動的Webプロジェクト(Java環境)
				・Tomcatプラグインプロジェクト対応
				・サンプルのHTMLとしてhifiveのStep3を含む
				・hifive v1.0.4を同梱
				</description>
			</info>
			<replace>
				<file name="/.jslint"/>
				<file name="/.codeassist"/>
				<file name="/.tomcatplugin"/>
				<file name="/.settings/org.eclipse.wst.common.component"/>
			</replace>
			<natures>
				<nature id="org.eclipse.jdt.core.javanature" name="java" />
				<nature id="com.sysdeo.eclipse.tomcat.tomcatnature"  name="tomcat"/>
			</natures>
		</base-project>
	</base-projects>
</libraries>
