=== hifive/hifivetools/eclipse/H5CodeAssistPluginCore/testPlugin/h5-code-assist.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">


    <xs:element name="h5-code-assist">
    	<xs:complexType>
    		<xs:sequence>
    			<xs:element name="codeassists" type="codeassists" maxOccurs="unbounded" minOccurs="0"></xs:element>
    		</xs:sequence>
    	</xs:complexType></xs:element>


    <xs:complexType name="codeassist">
        <xs:sequence>
            <xs:element name="argument" type="argument" maxOccurs="unbounded" minOccurs="0"></xs:element>
            <xs:element name="helpdoc" type="xs:string" maxOccurs="1" minOccurs="0">
    		</xs:element>
        </xs:sequence>
    	<xs:attribute name="method" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="returnType" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="codeassists">
    	<xs:sequence>
    		<xs:element name="codeassist" type="codeassist" maxOccurs="unbounded" minOccurs="1"></xs:element>
    	</xs:sequence>
    	<xs:attribute name="suffix" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="argument">
    	<xs:attribute name="name" type="xs:string" use="required"></xs:attribute>
    	<xs:attribute name="type" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>
</xs:schema>

=== hifive/hifivetools/eclipse/H5CodeAssistPluginCore/testPlugin/sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<h5-code-assist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="h5-code-assist.xsd">
	<codeassists suffix="Controller">
		<codeassist method="test1" returnType="ReturnType1">
			<argument name="arg1" type="Object" />
			<argument name="arg2" type="Object" />
			<helpdoc><![CDATA[<b>テストテスト</b>]]></helpdoc>
		</codeassist>
	</codeassists>
	<codeassists suffix="View">
		<codeassist returnType="ReturnType2" method="Test2">
			<argument name="arg" type="String" />
			<helpdoc>ああああああ</helpdoc>
		</codeassist>
	</codeassists>
</h5-code-assist>
